worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    
    upstream auth_service {
        server auth-service:8080;
    }
    
    upstream user_service {
        server user-service:8080;
    }
    
    upstream quiz_service {
        server quiz-service:8080;
    }
    
    upstream result_service {
        server result-service:8080;
    }
    
    upstream notification_service {
        server notification-service:8080;
    }

    server {
        listen 8080;

        # Auth Service
        location /register {
            proxy_pass http://auth_service;
        }
        location /login {
            proxy_pass http://auth_service;
        }

        # User Service
        location /users {
            proxy_pass http://user_service;
        }

        # Quiz Service
        location /quizzes {
            proxy_pass http://quiz_service;
        }

        # Result Service
        location /results {
            proxy_pass http://result_service;
        }

        # Notification Service
        location /notifications {
            proxy_pass http://notification_service;
        }
    }
}
